version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --replSet rs0
    networks:
      - my-network
    container_name: mongodb
    # Container para o MongoDB

  mysql:
    image: mysql:latest
    ports:
      - 33061:33061
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: bash -c "docker-entrypoint.sh --default-authentication-plugin=mysql_native_password && sleep 5 && mysql -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS database;'"
    networks:
      - my-network
    container_name: mysql
    # Container para o MySQL

  php-app:
    build:
      context: ./php-app
    ports:
      - 80:80
    networks:
      - my-network
    container_name: php-app
    # Container para o aplicativo PHP

  go-app:
    build:
      context: ./go-app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./go-app:/go/src/app
    networks:
      - my-network
    container_name: go-app
    # Container para o aplicativo Go

networks:
  my-network:
    # Rede personalizada para conectar os contêineres
