version: '3'
services:
  go-app:
    build:
      context: ./go-app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  php-app:
    build:
      context: ./php-app
    ports:
      - 80:80
  mongodb:
    image: mongo
    ports:
      - 27017:27017
